### ISSUE TITLE
Out of date!

### ISSUE THREAD

**Issue by ali** [ali/ali.io#3]
A lot of the information on the site is out of date.

## index.jade
- [x] I'm graduating August 31
- [x] The Google Glass photo of me is old. I have so many really nice new ones I can use.

## community.jade
This page reflects my involvement from middler/junior year, not any of the stuff I've done since then.

- [x] I'm not the president of NUACM anymore (term ended April 2014?)
- [x] I'm not a Hacks organizer anymore (involved from 2011 – 2015)
- [x] I'm not a Crew/UESG officer (involved 2011/2012 – 2015)
- [x] I "cofounded" HackBeanpot in 2013, captained it 2014, advised 2015 (@aliceyoung9 IM me if it's okay for me to say this or not, nbd)

**Comment by aliceyoung9** [comment]
Totally ok to say; also you mentored attendees!

**Comment by ali** [comment]
:+1:

**Comment by ali** [comment]
Fixed: 8a0a9767f00242e2cdfeaf72561093f8793a811d
